### ISSUE TITLE
Publish unpublished versions present in `main`

### ISSUE THREAD

**Issue by Klaim** [build2-packaging/imgui#22]
We had several versions merged recently in `main`:
- [ ] v1.90.6
- [ ] v1.90.7
- [x] v1.90.8

These versions are not yet tagged nor published on cppget.

(There is also the docking packages but it's not merged yet ~~and upstream also published another version recently v1.90.8.~~)

I created this issue so that the maintainers/reviewers keep can track of that, synchronize efforts and potentially to help @Rookfighter maintaining this.

@Rookfighter I'll take the liberty of proceeding to tag and publish these packages if you say you dont have the time or you dont manifest in the coming week 👍🏽

**Comment by wroyca** [comment]
> There is also the docking packages but it's not merged yet

Rebased to follow v1.90.8. \:)

**Comment by Rookfighter** [comment]
Thanks for the ticket. I added the tags and I will look into publishing v1.90.8 on cppget asap. Sorry for all the delay, currently I am less involved in build2.
IMO, if my responses take too long, feel free to also work in this repo without me. :+1:

**Comment by Klaim** [comment]
Noted, I just needed confirmation to avoid parallel duplicate work. Thanks for the recent versions, we'll try to handle the following ones when you're not around.

**Comment by Rookfighter** [comment]
bdep ci for v1.90.8: https://ci.cppget.org/@fe35edf6-fe1f-439c-85d5-d415acea1009

**Comment by Rookfighter** [comment]
queue.cppget v1.90.8: https://queue.cppget.org/libimgui

**Comment by Klaim** [comment]
Nobody requested the previous versions so far so I'll close this.
