### ISSUE TITLE
Publish "docking" packages

### ISSUE THREAD

**Issue by Klaim** [build2-packaging/imgui#23]
We just merged the `docking` upstream branch packages #19 

Now we need to publish them to cppget (as a revision I suppose?)

I will proceed this weekend if @Rookfighter isn't around 👍🏽

**Comment by Rookfighter** [comment]
Yeah, feel free to go ahead. I am on vacation, so I won't find the time to publish.
IMO revision +1 is the way to go

**Comment by Klaim** [comment]
Ok then I'll proceed soon 👍🏽

**Comment by Klaim** [comment]
Revision release tag done: https://github.com/build2-packaging/imgui/releases/tag/v1.90.8%2B1

**Comment by Klaim** [comment]
Revision release submitted:
- https://queue.cppget.org/libimgui/1.90.8+1
- https://queue.cppget.org/libimgui-docking/1.90.8+1
- https://queue.cppget.org/libimgui-platform-glfw/1.90.8+1
- https://queue.cppget.org/libimgui-platform-glfw-docking/1.90.8+1
- https://queue.cppget.org/libimgui-platform-osx/1.90.8+1
- https://queue.cppget.org/libimgui-platform-osx-docking/1.90.8+1
- https://queue.cppget.org/libimgui-platform-win32/1.90.8+1
- https://queue.cppget.org/libimgui-platform-win32-docking/1.90.8+1
- https://queue.cppget.org/libimgui-render-dx9/1.90.8+1
- https://queue.cppget.org/libimgui-render-dx9-docking/1.90.8+1
- https://queue.cppget.org/libimgui-render-dx10/1.90.8+1
- https://queue.cppget.org/libimgui-render-dx10-docking/1.90.8+1
- https://queue.cppget.org/libimgui-render-dx11/1.90.8+1
- https://queue.cppget.org/libimgui-render-dx11-docking/1.90.8+1
- https://queue.cppget.org/libimgui-render-dx12/1.90.8+1
- https://queue.cppget.org/libimgui-render-dx12-docking/1.90.8+1
- https://queue.cppget.org/libimgui-render-metal/1.90.8+1
- https://queue.cppget.org/libimgui-render-metal-docking/1.90.8+1
- https://queue.cppget.org/libimgui-render-opengl2/1.90.8+1
- https://queue.cppget.org/libimgui-render-opengl2-docking/1.90.8+1
- https://queue.cppget.org/libimgui-render-opengl3/1.90.8+1
- https://queue.cppget.org/libimgui-render-opengl3-docking/1.90.8+1
- https://queue.cppget.org/libimgui-render-vulkan/1.90.8+1
- https://queue.cppget.org/libimgui-render-vulkan-docking/1.90.8+1
- https://queue.cppget.org/libimgui-examples/1.90.8+1
- https://queue.cppget.org/libimgui-examples-docking/1.90.8+1
- https://queue.cppget.org/libimgui-null-backend-test/1.90.8+1
- https://queue.cppget.org/libimgui-null-backend-test-docking/1.90.8+1

A few additional notes:
This revision adds the docking packages, therefore it was theorically not necessary to add revision versions to the non-docking packages. In the same way of thinking, it was not necessary to mark the docking packages versions as revisions.
However, because these are all in the same repository and we want to keep things simple, I opted into not doing anything special about that and letting packages versions strictly match the related tagged git commit.
Worse case, package reviewers could just ignore the revision packages of the non-docking packages, it wouldnt change a thing for users.

Before publishing I double checked at least on Windows by building in configurations for msvc with debug and release kind of set of flags. Obviously in that context I couldnt build and test the osx platform packages nor the metal rendering packages, but it was still necessary to initialize these in the configurations to be able to `bdep publish`. FYI.

**Comment by wroyca** [comment]
Revision release submitted:

  - https://queue.cppget.org/libimgui/1.90.8+2
  - https://queue.cppget.org/libimgui-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-platform-glfw/1.90.8+2
  - https://queue.cppget.org/libimgui-platform-glfw-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-platform-osx/1.90.8+2
  - https://queue.cppget.org/libimgui-platform-osx-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-platform-win32/1.90.8+2
  - https://queue.cppget.org/libimgui-platform-win32-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-render-dx9/1.90.8+2
  - https://queue.cppget.org/libimgui-render-dx9-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-render-dx10/1.90.8+2
  - https://queue.cppget.org/libimgui-render-dx10-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-render-dx11/1.90.8+2
  - https://queue.cppget.org/libimgui-render-dx11-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-render-dx12/1.90.8+2
  - https://queue.cppget.org/libimgui-render-dx12-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-render-metal/1.90.8+2
  - https://queue.cppget.org/libimgui-render-metal-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-render-opengl2/1.90.8+2
  - https://queue.cppget.org/libimgui-render-opengl2-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-render-opengl3/1.90.8+2
  - https://queue.cppget.org/libimgui-render-opengl3-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-render-vulkan/1.90.8+2
  - https://queue.cppget.org/libimgui-render-vulkan-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-examples/1.90.8+2
  - https://queue.cppget.org/libimgui-examples-docking/1.90.8+2
  - https://queue.cppget.org/libimgui-null-backend-test/1.90.8+2
  - https://queue.cppget.org/libimgui-null-backend-test-docking/1.90.8+2

**Comment by wroyca** [comment]
Submitted:

  - https://queue.cppget.org/libimgui/1.90.9
  - https://queue.cppget.org/libimgui-docking/1.90.9
  - https://queue.cppget.org/libimgui-platform-glfw/1.90.9
  - https://queue.cppget.org/libimgui-platform-glfw-docking/1.90.9
  - https://queue.cppget.org/libimgui-platform-osx/1.90.9
  - https://queue.cppget.org/libimgui-platform-osx-docking/1.90.9
  - https://queue.cppget.org/libimgui-platform-win32/1.90.9
  - https://queue.cppget.org/libimgui-platform-win32-docking/1.90.9
  - https://queue.cppget.org/libimgui-render-dx9/1.90.9
  - https://queue.cppget.org/libimgui-render-dx9-docking/1.90.9
  - https://queue.cppget.org/libimgui-render-dx10/1.90.9
  - https://queue.cppget.org/libimgui-render-dx10-docking/1.90.9
  - https://queue.cppget.org/libimgui-render-dx11/1.90.9
  - https://queue.cppget.org/libimgui-render-dx11-docking/1.90.9
  - https://queue.cppget.org/libimgui-render-dx12/1.90.9
  - https://queue.cppget.org/libimgui-render-dx12-docking/1.90.9
  - https://queue.cppget.org/libimgui-render-metal/1.90.9
  - https://queue.cppget.org/libimgui-render-metal-docking/1.90.9
  - https://queue.cppget.org/libimgui-render-opengl2/1.90.9
  - https://queue.cppget.org/libimgui-render-opengl2-docking/1.90.9
  - https://queue.cppget.org/libimgui-render-opengl3/1.90.9
  - https://queue.cppget.org/libimgui-render-opengl3-docking/1.90.9
  - https://queue.cppget.org/libimgui-render-vulkan/1.90.9
  - https://queue.cppget.org/libimgui-render-vulkan-docking/1.90.9
  - https://queue.cppget.org/libimgui-examples/1.90.9
  - https://queue.cppget.org/libimgui-examples-docking/1.90.9
  - https://queue.cppget.org/libimgui-null-backend-test/1.90.9
  - https://queue.cppget.org/libimgui-null-backend-test-docking/1.90.9
