### ISSUE TITLE
Issue with the submitted `1.90.8+1` docking packages

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/imgui#24]
The `libimgui-docking` package in queue doesn't have a single successful build: https://queue.cppget.org/?builds=libimgui-docking

Which means it cannot be moved to cppget.org per the policy unless there is a good explanation for the failures (though seeing that quite a few of the failures are on the `test-installed` step, I doubt we can justify them).

In contrast, the non-docking version seems to build successfully on about half of the configurations: https://queue.cppget.org/?builds=libimgui

BTW, per the packaging guide: https://build2.org/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-release-publish-publish

> The bdep-publish command prepares the source distribution of your package, uploads the resulting archive to the package repository, and prints a link to the package submission in the queue. **Open this link in the browser and check that there are no surprises in the build results**  [...]

**Comment by wroyca** [comment]
> The `libimgui-docking` package in queue doesn't have a single successful build: https://queue.cppget.org/?builds=libimgui-docking
> 
> Which means it cannot be moved to cppget.org per the policy unless there is a good explanation for the failures (though seeing that quite a few of the failures are on the `test-installed` step, I doubt we can justify them).
> 
> In contrast, the non-docking version seems to build successfully on about half of the configurations: https://queue.cppget.org/?builds=libimgui
> 
> BTW, per the packaging guide: https://build2.org/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-release-publish-publish
> 
> > The bdep-publish command prepares the source distribution of your package, uploads the resulting archive to the package repository, and prints a link to the package submission in the queue. **Open this link in the browser and check that there are no surprises in the build results**  [...]

Uh. That's odd, tests were definitely passing previously. Will take a look, thank!

**Comment by wroyca** [comment]
Quick log survey show that half of it is due to vulkan header not being found, the other half is ```libimgui-null-backend-test-docking``` not finding imgui.h

**Comment by wroyca** [comment]
Thank! This should be fixed as soon as the MR land :+1:

**Comment by Klaim** [comment]
> BTW, per the packaging guide: https://build2.org/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-release-publish-publish
> 
> > The bdep-publish command prepares the source distribution of your package, uploads the resulting archive to the package repository, and prints a link to the package submission in the queue. **Open this link in the browser and check that there are no surprises in the build results**  [...]

I did and started investigating immediately but didnt reach a solution before my time on it ran out (I wont be available for a few days), thanks for reporting.
Thanks @wroyca for checking it!
